// Quiz & scoring functions — extracted from app/page.js
import{DIMS,DM}from"./constants.js";

export const starsFromEnergy=(e)=>{if(e>=85)return 5;if(e>=70)return 4;if(e>=52)return 3;if(e>=35)return 2;return 1};
export const starStr=(n)=>{let s='';for(let i=0;i<n;i++)s+='⭐';for(let i=n;i<5;i++)s+='☆';return s};
export const starLabel=(n)=>['','เดือนยาก','เดือนระวัง','เดือนปกติ','เดือนดี','เดือนทอง'][n]||'';
export const starLabelEN=(n)=>['','Hard Month','Caution Month','Normal Month','Good Month','Golden Month'][n]||'';

export const calcMBTI=(s)=>{const ei=((s["Energy Management"]||5)+(s["Motivation Driver"]||5))/2>=5.5?"E":"I";const ns=((s["Cognitive Processing"]||5)+(s["Integration Level"]||5)+(s["Growth Orientation"]||5))/3>=5.5?"N":"S";const tf=(s["Decision System"]||5)>=(s["Emotional Regulation"]||5)?"T":"F";const jp=((s["Identity Stability"]||5)+(s["Responsibility Load"]||5))/2>=5.5?"J":"P";return ei+ns+tf+jp};

export const calcDomPlanet=(v)=>{const pMap={"Cognitive Processing":"พุธ","Emotional Regulation":"จันทร์","Identity Stability":"อาทิตย์","Energy Management":"อังคาร","Decision System":"พฤหัส","Responsibility Load":"เสาร์","Motivation Driver":"อาทิตย์","Boundary System":"เสาร์","Stress Response":"เสาร์","Shadow Pattern":"ราหู","Growth Orientation":"พฤหัส","Integration Level":"พุธ"};const pMeta={"พุธ":{en:"Mercury",icon:"⚡",power:"ปัญญาเฉียบแหลม สื่อสารชั้นยอด"},"จันทร์":{en:"Moon",icon:"🌙",power:"เข้าใจอารมณ์คน สร้างความไว้วางใจ"},"อาทิตย์":{en:"Sun",icon:"☀️",power:"ความเป็นผู้นำและความมั่นใจสูง"},"อังคาร":{en:"Mars",icon:"🔴",power:"พลังนักรบ ลงมือทำไม่รอช้า"},"พฤหัส":{en:"Jupiter",icon:"🟡",power:"ปัญญาเปิดกว้าง ดึงดูดโชคและโอกาส"},"ศุกร์":{en:"Venus",icon:"💚",power:"ดึงดูดคน สร้างความร่วมมือ"},"เสาร์":{en:"Saturn",icon:"🪐",power:"วินัยสูง สร้างสิ่งยั่งยืน"},"ราหู":{en:"Rahu",icon:"🌑",power:"ทลายขีดจำกัด สร้างสิ่งที่ไม่เคยมีมาก่อน"}};const sorted=Object.entries(v||{}).sort((a,b)=>b[1]-a[1]);const topDim=sorted[0]?.[0]||"Cognitive Processing";const pName=pMap[topDim]||"พฤหัส";return{planet:pName,...(pMeta[pName]||pMeta["พฤหัส"])}};

export const calcV=(bd,ts)=>{const m=parseInt(bd?.split("-")?.[1])||6;const d=parseInt(bd?.split("-")?.[2])||15;const s=(m*31+d)%100;const tb={dawn:5,morning:3,noon:0,evening:2,night:-2}[ts]||0;const ps={me:Math.min(40,20+(s%20)+tb),mo:Math.min(40,18+((s*3)%22)+tb),su:Math.min(40,22+((s*7)%18)+tb),ma:Math.min(40,19+((s*11)%21)+tb),ju:Math.min(40,21+((s*13)%19)+tb),sa:Math.min(40,17+((s*17)%23)+tb),ra:Math.min(40,15+((s*19)%25)+tb)};const f=(p,i)=>Math.min(100,p+Math.min(25,10+((s+i)%15))+Math.min(20,8+((s*2+i)%12))+Math.min(15,5+((s*3+i)%10)));return{"Cognitive Processing":f(ps.me,1)/10,"Emotional Regulation":f(ps.mo,2)/10,"Identity Stability":f(Math.round((ps.su+ps.sa)/2),3)/10,"Energy Management":f(ps.ma,4)/10,"Decision System":f(Math.round((ps.ju+ps.sa)/2),5)/10,"Responsibility Load":f(ps.sa,6)/10,"Motivation Driver":f(ps.su,7)/10,"Boundary System":f(Math.round((ps.sa+ps.mo)/2),8)/10,"Stress Response":f(ps.sa,9)/10,"Shadow Pattern":f(ps.ra,10)/10,"Growth Orientation":f(ps.ju,11)/10,"Integration Level":f(Math.round(Object.values(ps).reduce((a,b)=>a+b,0)/7),12)/10}};
export const calcS=(v,ans)=>{const sc={};DIMS.forEach(dim=>{const vd=v[dim]||5;let raw=0,cnt=0;const dd=DM[dim];if(dd)dd.q.forEach((_,i)=>{const k=`${dim}-${i}`;if(ans[k]!==undefined){let val=ans[k];if(dd.rev)val=4-val;raw+=val;cnt++}});const ap=cnt>0?(raw/(cnt*4))*10:5;let fi=vd*.6+ap*.4;if(vd>7&&ap<4)fi-=1.5;if(vd<4&&ap>7)fi+=.5;sc[dim]=Math.max(0,Math.min(10,Math.round(fi*10)/10))});return sc};
